stages:
    - build
    - test

# https://stackoverflow.com/questions/62689235/gitlab-ci-how-to-ignore-directory-using-rules-syntax
build-job:
    stage: build
    rules:
        - changes:
            - .ci/
            - packaging/
            - go/
            - rpmbuild/
          when: never
        - when: on_success
    tags: [ k8s, mtr, linux, x86_64 ]
    # image: harbor.mellanox.com/swx-storage/spdk/x86_64/oraclelinux-8-spdk_dev:20240228c
    image: harbor.mellanox.com/swx-storage/spdk/x86_64/fedora39-spdk_dev:20240228
    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        GIT_SUBMODULE_DEPTH: 1
    hooks:
      pre_get_sources_script:
        - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/Mellanox/spdk_team/dpdk.git".insteadOf https://github.com/spdk/dpdk.git
    script:
        # do git submodule explicitly: we need to replace URL for dpdk
        # - git config -f .gitmodules remote.dpdk.url https://gitlab.com/Mellanox/spdk_team/dpdk.git
        #- git submodule update --init
        # GET FIO source, run ./configure
        - (cd .. ; curl -LO https://github.com/axboe/fio/archive/refs/tags/fio-3.35.tar.gz; tar xf fio-3.35.tar.gz)
        - cd ../fio-fio-3.35
        - ./configure --prefix=/usr/local
        - cd $CI_PROJECT_DIR
        - ./scripts/check_format.sh
        - ./configure --with-fio=../fio-fio-3.35/ --with-rdma=mlx5_dv --disable-unit-tests --target-arch=znver3
        - make -j4
        - find test -type f -perm 0755 |egrep -v '\.sh|\.py|\.pl|\/match' |tar cf .test.tar -T /dev/stdin
    artifacts:
        expire_in: 1 week
        paths:
          - ./build
          - ./dpdk/build/
          - .test.tar
          - ./mk/config.mk
          - ./mk/cc.mk

test-job:
    stage: test
    rules:
        - changes:
            - .ci/
            - packaging/
            - go/
            - rpmbuild/
          when: never
        - when: on_success
    tags: [ vm, mtr, linux, x86_64, f39 ]
#    variables:
#        GIT_CHECKOUT: "false"
#        GIT_CLEAN_FLAGS: "none"
    script:
        - patch -p1 < $HOME/spdk-test-nvme.diff
        - tar xf .test.tar
          # clean up output of autotest from previous runs
        - sudo rm -rf $CI_PROJECT_DIR/../output/
          # - sudo ./test/unit/unittest.sh
        - sudo ./autotest.sh $HOME/autorun-spdk.conf
        - sudo chown -R $USER $CI_PROJECT_DIR
########
