FROM dockerhub.nvidia.com/rockylinux:9.2
ARG _UID=6213
ARG _GID=11429
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
ARG DOCA_VER
ENV LANG=en_US.utf-8
USER root

RUN yum install -y ca-certificates

RUN yum install -y \
    epel-release

RUN yum install --enablerepo=crb -y \
    sudo \
    git \
    wget \
    vim \
    fakeroot \
    ncurses-devel \
    rpm-build doxygen \
    graphviz \
    numactl-devel \
    libiscsi-devel \
    make \
    gcc \
    CUnit-devel \
    libaio-devel \
    openssl-devel \
    libuuid-devel \
    gcc-c++ \
    python39 \
    meson \
    python3-pip \
    python3-configshell \
    pkgconfig autoconf automake libtool \
    fuse3-devel patchelf

RUN set -eux; \
    echo -e "[doca]\n\
name=NVIDIA DOCA \$basearch\n\
baseurl=https://linux.mellanox.com/public/repo/doca/${DOCA_VER}/rhel9/arm64-sbsa/\n\
enabled=1\n\
gpgcheck=1\n\
repo_gpgcheck=1\n\
gpgkey=https://linux.mellanox.com/public/repo/doca/${DOCA_VER}/rhel9/arm64-sbsa/RPM-GPG-KEY-doca" > /etc/yum.repos.d/nvidia_doca.repo; \
    yum install -y doca-ofed-userspace

RUN pip3 install --prefix=/usr/ pyelftools

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN mkdir -p $_HOME
RUN groupadd -f -g "$_GID" "$_LOGIN"
RUN useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "$_LOGIN"
RUN chown $_LOGIN $_HOME
RUN yum clean all

SHELL ["/bin/bash"]
USER "${_LOGIN}"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
