FROM dockerhub.nvidia.com/ubuntu:24.04
ARG _UID=6213
ARG _GID=11429
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
ARG DEBIAN_FRONTEND=noninteractive
ARG DOCA_VER
ENV TZ=Etc/UTC
USER root

RUN apt-get update && \
    apt-get install -y \
      git \
      vim \
      wget \
      curl \
      python3 \
      dpkg-dev \
      sudo \
      debhelper \
      debsigs \
      autotools-dev \
      dh-python \
      libiscsi-dev \
      meson \
      uuid-dev \
      libssl-dev \
      libaio-dev \
      libncurses-dev \
      libcunit1-dev \
      patchelf \
      python3-pyelftools \
      python3-requests \
      python3-pip \
      liburing-dev \
      linux-headers-generic \
      pkg-config nasm \
      libnuma-dev \
      libfuse3-dev \
      lsb-release

RUN set -eux; \
    echo "deb [trusted=yes] https://linux.mellanox.com/public/repo/doca/${DOCA_VER}/ubuntu24.04/arm64-sbsa/ ./" > /etc/apt/sources.list.d/doca.list && \
    apt-get update && \
    apt-get install -y doca-ofed-userspace libxlio-dev

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN mkdir -p $_HOME
RUN groupadd -f -g "$_GID" "$_LOGIN"
RUN useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "$_LOGIN"
RUN chown $_LOGIN $_HOME

SHELL ["/bin/bash"]

USER "${_LOGIN}"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
