# Original CTYUNOS 23.01 image:
# https://repo.ctyun.cn/hostos/ctyunos-23.01/docker_img/aarch64/ctyunos3-docker-230117-aarch64.tar.xz
FROM nbu-harbor.gtm.nvidia.com/sw-linux-devops/bfb_builder_ctyunos23.01
ARG _UID=6213
ARG _GID=11429
ARG _LOGIN=swx-jenkins
ARG _HOME=/var/home/$_LOGIN
ARG DOCA_VER
ENV LANG=en_US.utf-8
USER root

RUN yum install -y \
    sudo \
    git \
    wget \
    vim \
    fakeroot \
    ncurses-devel \
    rpm-build doxygen \
    graphviz \
    numactl-devel \
    libiscsi-devel \
    make \
    gcc \
    CUnit-devel \
    libaio-devel \
    openssl-devel \
    libuuid-devel \
    gcc-c++ \
    python39 \
    meson \
    python3-pip \
    python3-configshell \
    pkgconfig autoconf automake libtool \
    fuse3-devel patchelf

RUN set -eux; \
    echo -e "[doca]\n\
name=NVIDIA DOCA \$basearch\n\
baseurl=https://linux.mellanox.com/public/repo/doca/${DOCA_VER}/ctyunos23.01/arm64-sbsa/\n\
enabled=1\n\
gpgcheck=1\n\
repo_gpgcheck=1\n\
gpgkey=https://linux.mellanox.com/public/repo/doca/${DOCA_VER}/ctyunos23.01/arm64-sbsa/RPM-GPG-KEY-doca" > /etc/yum.repos.d/nvidia_doca.repo; \
    yum install -y doca-ofed-userspace libxlio libxlio-devel

RUN pip3 install --prefix=/usr/ pyelftools

RUN echo "${_LOGIN} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN mkdir -p $_HOME
RUN groupadd -f -g "$_GID" "$_LOGIN"
RUN useradd -u "$_UID" -g "$_GID" -s /bin/bash -m -d ${_HOME} "$_LOGIN"
RUN chown $_LOGIN $_HOME
RUN yum clean all

SHELL ["/bin/bash"]
USER "${_LOGIN}"
ENTRYPOINT [ "/bin/bash", "--login", "--rcfile", "/etc/bashrc", "-c" ]
